# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import metadata_pb2 as metadata__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in metadata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetadataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSong = channel.unary_unary(
                '/metadata.MetadataService/AddSong',
                request_serializer=metadata__pb2.AddSongRequest.SerializeToString,
                response_deserializer=metadata__pb2.SongResponse.FromString,
                _registered_method=True)
        self.GetSongMetadata = channel.unary_unary(
                '/metadata.MetadataService/GetSongMetadata',
                request_serializer=metadata__pb2.SongRequest.SerializeToString,
                response_deserializer=metadata__pb2.SongResponse.FromString,
                _registered_method=True)
        self.GetSongPath = channel.unary_unary(
                '/metadata.MetadataService/GetSongPath',
                request_serializer=metadata__pb2.SongRequest.SerializeToString,
                response_deserializer=metadata__pb2.SongPathResponse.FromString,
                _registered_method=True)


class MetadataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSongMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSongPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSong': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSong,
                    request_deserializer=metadata__pb2.AddSongRequest.FromString,
                    response_serializer=metadata__pb2.SongResponse.SerializeToString,
            ),
            'GetSongMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSongMetadata,
                    request_deserializer=metadata__pb2.SongRequest.FromString,
                    response_serializer=metadata__pb2.SongResponse.SerializeToString,
            ),
            'GetSongPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSongPath,
                    request_deserializer=metadata__pb2.SongRequest.FromString,
                    response_serializer=metadata__pb2.SongPathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metadata.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metadata.MetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata.MetadataService/AddSong',
            metadata__pb2.AddSongRequest.SerializeToString,
            metadata__pb2.SongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSongMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata.MetadataService/GetSongMetadata',
            metadata__pb2.SongRequest.SerializeToString,
            metadata__pb2.SongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSongPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata.MetadataService/GetSongPath',
            metadata__pb2.SongRequest.SerializeToString,
            metadata__pb2.SongPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
