# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\x12\x08metadata\"#\n\x0e\x41\x64\x64SongRequest\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\"\x1e\n\x0bSongRequest\x12\x0f\n\x07song_id\x18\x01 \x01(\t\"\x91\x01\n\x0cSongResponse\x12\x0f\n\x07song_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05\x61lbum\x18\x04 \x01(\t\x12\x0c\n\x04year\x18\x05 \x01(\t\x12\r\n\x05genre\x18\x06 \x01(\t\x12\x10\n\x08\x64uration\x18\x07 \x01(\x01\x12\x13\n\x0b\x61lbum_cover\x18\x08 \x01(\x0c\" \n\x10SongPathResponse\x12\x0c\n\x04path\x18\x01 \x01(\t2\xd2\x01\n\x0fMetadataService\x12;\n\x07\x41\x64\x64Song\x12\x18.metadata.AddSongRequest\x1a\x16.metadata.SongResponse\x12@\n\x0fGetSongMetadata\x12\x15.metadata.SongRequest\x1a\x16.metadata.SongResponse\x12@\n\x0bGetSongPath\x12\x15.metadata.SongRequest\x1a\x1a.metadata.SongPathResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDSONGREQUEST']._serialized_start=28
  _globals['_ADDSONGREQUEST']._serialized_end=63
  _globals['_SONGREQUEST']._serialized_start=65
  _globals['_SONGREQUEST']._serialized_end=95
  _globals['_SONGRESPONSE']._serialized_start=98
  _globals['_SONGRESPONSE']._serialized_end=243
  _globals['_SONGPATHRESPONSE']._serialized_start=245
  _globals['_SONGPATHRESPONSE']._serialized_end=277
  _globals['_METADATASERVICE']._serialized_start=280
  _globals['_METADATASERVICE']._serialized_end=490
# @@protoc_insertion_point(module_scope)
