"""remove profile_picture

Revision ID: 337f5e426726
Revises: b7c2e1f3a4d6
Create Date: 2025-10-25 01:54:29.946467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '337f5e426726'
down_revision: Union[str, Sequence[str], None] = 'b7c2e1f3a4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("profile_picture")

    op.drop_index(op.f('ix_playlist_likes_playlist_id'), table_name='playlist_likes')
    op.drop_index(op.f('ix_playlist_likes_user_id'), table_name='playlist_likes')
    op.drop_table('playlist_likes')

    op.drop_index(op.f('ix_playlist_id'), table_name='playlist')
    op.drop_table('playlist')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('playlist_likes_playlist_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('playlist_likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id', name=op.f('playlist_likes_pkey'))
    )
    op.create_index(op.f('ix_playlist_likes_user_id'), 'playlist_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_playlist_likes_playlist_id'), 'playlist_likes', ['playlist_id'], unique=False)
    op.create_table('playlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('playlist_cover', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('playlist_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_pkey'))
    )
    op.create_index(op.f('ix_playlist_id'), 'playlist', ['id'], unique=False)
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=False, server_default='avatar1.png'))
    # ### end Alembic commands ###
