"""create_playlist_and_likes

Revision ID: b7c2e1f3a4d6
Revises: 93d69820fccc
Create Date: 2025-10-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c2e1f3a4d6'
down_revision = '93d69820fccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('playlist_cover', sa.LargeBinary(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True, server_default=sa.text('false')),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.text('true')),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_id'), 'playlist', ['id'], unique=False)

    op.create_table('playlist_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id')
    )
    op.create_index(op.f('ix_playlist_likes_playlist_id'), 'playlist_likes', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_likes_user_id'), 'playlist_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_likes_user_id'), table_name='playlist_likes')
    op.drop_index(op.f('ix_playlist_likes_playlist_id'), table_name='playlist_likes')
    op.drop_table('playlist_likes')
    op.drop_index(op.f('ix_playlist_id'), table_name='playlist')
    op.drop_table('playlist')
    # ### end Alembic commands ###
